# Generated by Django 5.1 on 2024-09-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_alter_record_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
