# Generated by Django 5.1 on 2024-09-04 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_alter_department_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='content',
        ),
    ]
