# Generated by Django 5.1 on 2024-09-01 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='secret_key',
        ),
    ]
